#FROM docker.io/library/golang:1-alpine AS builder
#
#RUN apk update && apk add --no-cache build-base ca-certificates
#
#WORKDIR /src
#COPY main.go .
#RUN go build -trimpath --ldflags '-s -w' -o redirect main.go

FROM alpine:3.13

LABEL org.wabarc.homepage="http://github.com/wabarc"

RUN set -o pipefail && \
    apk add --no-cache \
    dbus \
    dumb-init \
    supervisor \
    ca-certificates \
    py3-setuptools \
    tor \
    curl \
    socat \
    libcap \
 && cp /etc/tor/torrc.sample /etc/tor/torrc \
 && echo 'SocksPort 9050' >> /etc/tor/torrc \
 && echo 'ClientOnly 1' >> /etc/tor/torrc \
 && setcap 'cap_net_bind_service=+ep' /usr/bin/socat \
 && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

#COPY --from=builder /src/redirect /usr/local/bin/
COPY supervisord.conf /etc/
COPY echo.sh /

# Set Tor Hidden Service default value
ENV TOR_HOST=wabarcoww2bxmdbixj7sjwggv3fonh2rpflfiildegcydk5udkdckdyd.onion:80
ENV SOCAT_OPTIONS="-d"
ENV PORT=80

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dumb-init", "--"]

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

HEALTHCHECK --interval=5m --start-period=30s \
  CMD curl -f http://localhost:$PORT/ || exit 1
